### ISSUE TITLE
Zaimplementowanie AI przeciwników

### ISSUE THREAD

**Issue by 4rgorok** [4rgorok/pacman-maker#6]
4h, shortest path

**Comment by PiotrekHofman** [comment]
1 shortest path 4h
2 original  10
3 losowe lowy keirunek aż nie napotka przeszkody i zmiana 1
4 inne targetowanie (duzesz biega z iinym duszkiem) 1
5 parametryzowanie jak często odczytuję gdzie jest mój target 2
6 różne kolory różne AI 2
